# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # Setting versions based on this table: https://github.com/ewanharris/vscode-versions
        node_version: [18, 20]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: npm install
    - name: Prepare environment
      run: |
        npm install -g typescript
        npm install -g vsce
    - name: Build
      run: npm run compile
    - name: Smoke test (Linux)
      run: xvfb-run -a npm run test
      if: runner.os == 'Linux'
    # Windows tests are failing to install the VS Code extension: https://github.com/microsoft/vscode-test/tree/main. Disabling for now.
    # - name: Smoke test (Windows)
    # run: npm run test
    # if: runner.os == 'Windows'
    # - name: Smoke test (Mac)
    #   run: npm run test
    #   if: runner.os == 'macOS'
    - name: Package extension
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == 18
      run: |
        vsce package
        mkdir vsix
        mv *.vsix vsix
    - name: Archive extension
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == 18
      uses: actions/upload-artifact@v4
      with:
        name: vsix
        path: vsix
