# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [14, 16]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: npm install
    - name: Prepare environment
      run: |
        npm install -g typescript
        npm install -g vsce
    - name: Build
      run: npm run compile
    - name: Smoke test (Linux)
      run: xvfb-run -a npm run test
      if: runner.os == 'Linux'
    - name: Smoke test (Mac, Windows)
      run: npm run test
      if: runner.os != 'Linux'
    - name: Package extension
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == 14
      run: |
        vsce package
        mkdir vsix
        mv *.vsix vsix
    - name: Archive extension
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == 14
      uses: actions/upload-artifact@v1
      with:
        name: vsix
        path: vsix
